---
title: "p8105_hw6_mfc2162"
author: "Madeline Cannon"
date: "11/17/2019"
output: github_document
---

```{r}

library(tidyverse)

```


```{r}

birthweight = read_csv("./data/birthweight.csv") %>%
  mutate(babysex = as.factor(recode(babysex, "1" = "male", "2" = "female"))) %>%
  mutate(frace = as.factor(recode(frace, "1" = "White",
                                          "2" = "Black",
                                          "3" = "Asian",
                                          "4" = "Puerto Rican",
                                          "8" = "Other",
                                          "9" = "Unknown"))) %>%
  mutate(malform = as.factor(recode(malform, "0" = "absent", "1" = "present"))) %>%
  mutate(mrace = as.factor(recode(mrace, "1" = "White",
                                          "2" = "Black",
                                          "3" = "Asian",
                                          "4" = "Puerto Rican",
                                          "8" = "Other",
                                          "9" = "Unknown")))

```